### ISSUE TITLE
Add "normal" feed support to Changes

### ISSUE THREAD

**Issue by tburke** [go-kivik/couchdb#168]
Make the Changes call support the "normal", paginated feed.

**Comment by flimzy** [comment]
Thanks for the suggestion (and PR).  I'm not sure why I chose to limit this implementation early on.  I'll look over the PR shortly.

One question: You mention "paginated feed"... I don't see any pagination feature, per se, in CouchDB. It seems like the 'normal' mode just returns all changes, since the beginning of time. Was there something specific you were referring to with the pagination?

**Comment by flimzy** [comment]
This should now be done for for all supported drivers:
- Frontend support: https://github.com/go-kivik/kivik/pull/379
- CouchDB: https://github.com/go-kivik/couchdb/pull/175
- PouchDB: https://github.com/go-kivik/pouchdb/pull/43
- Mock driver: https://github.com/go-kivik/kivikmock/pull/53
