### ISSUE TITLE
Errors trying to PUT doc to Cloudant via HTTPS

### ISSUE THREAD

**Issue by tleyden** [go-kivik/couchdb#79]
This started happening all of the sudden at Mon, Feb 12, 2018 at 10:00 AM, with no known changes on my end.  I'm not sure if Cloudant changed something on their end.  I filed a support issue with them, but got the response:

> Can you reproduce the problem using the Cloudant API or any of the supported client libraries that are listed at
 https://console.bluemix.net/docs/services/Cloudant/libraries/supported.html#supported-client-libraries    
> There should be no difference in the result of requests whether the protocol used is HTTP or HTTPS.

After digging into it, I'm able to reproduce with this test code:

https://github.com/tleyden/keynuker/blob/18143d259c6711aacf0e4e75af84d5501b143df7/write_doc_test.go#L16-L105

The errors in the logs are: https://gist.github.com/tleyden/bde26a0fe25eae17a752d5e636547318 (which includes some log messages that I haven't pushed up to github)

and I'm on the following commits for the go-kivik driver libraries:

* go-kivik/couchdb commit b05fce5e384b7a2b51a9dd698065042f66c322d4  Tue Dec 26 15:21:07 2017 +0100 (I later updated to 74d231fe43245e77840213724894264f0f61ffd3)

* go-kivik/kivik commit d573df18e22d55cffe07dd8dc43c0aac2104b91a Fri Dec 22 19:31:25 2017 +0100 (I later updated to 9f4809d02c708b15465454aeef571901c4f9917b)

If I switch to HTTP, with no other changes, the problem goes away.  Here are the logs from that same test after switching to HTTP: https://gist.github.com/tleyden/2c4ec6dbee9d0b4dfa9e606ea647e0e8

**Comment by tleyden** [comment]
This workaround in https://github.com/go-kivik/couchdb/blob/master/chttp/chttp.go#L166-L185 seems to fix it:

```
// DoReq does an HTTP request. An error is returned only if there was an error
// processing the request. In particular, an error status code, such as 400
// or 500, does _not_ cause an error to be returned.
func (c *Client) DoReq(ctx context.Context, method, path string, opts *Options) (*http.Response, error) {
	if method == "" {
		return nil, errors.Status(kivik.StatusBadRequest, "chttp: method required")
	}
	var body io.Reader
	if opts != nil {
		if opts.Body != nil {
			body = opts.Body
		}
	}

	// read the whole body into a string

	var destBody io.Reader
	destBody = body

	if body != nil {

		entireBody, err := ioutil.ReadAll(body)
		if err != nil {
			log.Printf("Error reading body: %v", err)
		}
		log.Printf("body size: %d bytes", len(entireBody))

		body2 := bytes.NewBuffer(entireBody)
		destBody = body2

	}

	req, err := c.NewRequest(ctx, method, path, destBody)
	if err != nil {
		return nil, err
	}
	fixPath(req, path)
	setHeaders(req, opts)

	response, err := c.Do(req)
	return response, netError(err)
}
```

Logs: https://gist.github.com/tleyden/d5f65db9d39e08e581b274515a235442

**Comment by flimzy** [comment]
Thanks for reporting this. I'll try to reproduce it myself to come to an understanding of the root cause, and come up with an ideal fix.

**Comment by rnewson** [comment]
Hi. the root cause is not sending a Content-Length header.

At cloudant we have haproxy 1.8.x in front, providing http/2 support. I reported the problem to haproxy at https://www.mail-archive.com/haproxy@formilux.org/msg29137.html and Willy agrees that haproxy should convert http/2 request bodies to the http 1.1 chunked transfer encoding.

the http/2 spec allows you to omit Content-Length header but does not prohibit it. In my tests, simply adding the Content-Length header (with the right value, of course) fixes this issue. Other http tools, like curl, send this header even for http/2.

**Comment by flimzy** [comment]
Thanks for explanation, @rnewson. That should be easy enough to fix.

**Comment by flimzy** [comment]
I finally have some time today to look into this, and my first step is to investigate whether an alternative to the `Content-Length` header can be reasonably used, to avoid having to read the entire response into a buffer before sending it to the server.  @rnewson, it looks like you've already done some research on this, with respect to the haproxy issue linked above.  Have you found any reasonable alternative?  Would a `Content-Encoding: chunked` header, for instance, work around the problem?

For most HTTP requests, reading the entire request body into memory to calculate the size won't be a big deal, but for some requests (documents with large attachments, bulk POSTs, etc), it would obviously be desirable not to have to calculate the request size ahead of time.

If chunked encoding won't work for these requests, I may look into a method for optionally enabling the behavior of pre-calculating the request length, so that non-Cloudant/haproxy users won't be penalized.

**Comment by flimzy** [comment]
The existing test suite for Kivik fails against Cloudant, as explained in this issue.  For example:

    $ go test ./test -v -run=TestCloudant/CreateDoc/RW/group/Admin/WithID
    === RUN   TestCloudant
    === RUN   TestCloudant/CreateDoc
    === RUN   TestCloudant/CreateDoc/RW
    === RUN   TestCloudant/CreateDoc/RW/group
    === RUN   TestCloudant/CreateDoc/RW/group/Admin
    === RUN   TestCloudant/CreateDoc/RW/group/Admin/WithID
    --- FAIL: TestCloudant (2.55s)
            test.go:403: Connecting to https://<redacted>@4cf04ee5-64ee-4c87-8853-4a171963b5a1-bluemix.cloudant.com/ ...
            test.go:415: Connecting to https://4cf04ee5-64ee-4c87-8853-4a171963b5a1-bluemix.cloudant.com/ ...
        --- FAIL: TestCloudant/CreateDoc (0.61s)
            --- FAIL: TestCloudant/CreateDoc/RW (0.61s)
                --- FAIL: TestCloudant/CreateDoc/RW/group (0.00s)
                    --- FAIL: TestCloudant/CreateDoc/RW/group/Admin (0.00s)
                        --- FAIL: TestCloudant/CreateDoc/RW/group/Admin/WithID (0.20s)
                            kt.go:261: Unexpected failure: 400/Bad Request: Missing request body
    FAIL
    exit status 1
    FAIL    github.com/go-kivik/couchdb/test        2.552s

@tleyden's work-around linked above is confirmed to fix it, but this not an ideal solution in my opinion, as it will make handling large requests inefficient, so I'm continuing to look for an alternative. Suggestions welcome!

**Comment by flimzy** [comment]
Downgrading the connection to HTTP 1.1 solves the problem, too:

    $ GODEBUG=http2client=0 go test ./test -v -run=TestCloudant/CreateDoc/RW/group/Admin/WithID
    === RUN   TestCloudant
    === RUN   TestCloudant/CreateDoc
    === RUN   TestCloudant/CreateDoc/RW
    === RUN   TestCloudant/CreateDoc/RW/group
    === RUN   TestCloudant/CreateDoc/RW/group/Admin
    === RUN   TestCloudant/CreateDoc/RW/group/Admin/WithID
    --- PASS: TestCloudant (4.08s)
            test.go:403: Connecting to https://<redacted>@4cf04ee5-64ee-4c87-8853-4a171963b5a1-bluemix.cloudant.com/ ...
            test.go:415: Connecting to https://4cf04ee5-64ee-4c87-8853-4a171963b5a1-bluemix.cloudant.com/ ...
        --- PASS: TestCloudant/CreateDoc (1.22s)
            --- PASS: TestCloudant/CreateDoc/RW (1.22s)
                --- PASS: TestCloudant/CreateDoc/RW/group (0.00s)
                    --- PASS: TestCloudant/CreateDoc/RW/group/Admin (0.00s)
                        --- PASS: TestCloudant/CreateDoc/RW/group/Admin/WithID (0.82s)
    PASS
    ok      github.com/go-kivik/couchdb/test        4.087s

I don't believe there's any supported way to disable HTTP/2 in the Go `http` package beyond that debug flag, though.

**Comment by flimzy** [comment]
I found a way to disable HTTP/2 support on a per-request basis.  #80 provides a POC, and a work-around (probably more efficient than yours, @tleyden--if you're inclined to try my approach, I'd be curious to hear any feedback).

Next step is probably to use the work-around only for affected requests (i.e. PUT and POST requests), so that all others can still benefit from HTTP/2, where applicable.

Then I need to devise a method to either auto-detect when the work-around is appropriate (can probably be done by detecting Cloudant headers in HTTP responses), or enabling the work-around with some sort of configuration, or possibly both options.

**Comment by rnewson** [comment]
@flimzy I just tested, a chunked transfer encoding is handled even worse, a new and separate haproxy bug which I will report.

I'm not familiar with Go at all but I'm looking at https://github.com/go-kivik/couchdb/blob/master/db.go#L294. Is it not possible to cheaply calculate the serialized size of `doc` as you have it right there? I appreciate you can't calculate Content-Length for a streamed input, but you could in all cases where you have the data as a variable.

The real fix will be for haproxy. Clearly it doesn't do the right thing for http/2 -> http 1.1 request bodies.

**Comment by flimzy** [comment]
> I'm not familiar with Go at all but I'm looking at https://github.com/go-kivik/couchdb/blob/master/db.go#L294. Is it not possible to cheaply calculate the serialized size of doc as you have it right there?

Unfortunately, no. That call to `chttp.EncodeBody` returns a stream, which is serialized in real-time in a go routine, as the request is being sent.  See the function [here](https://github.com/go-kivik/couchdb/blob/master/chttp/chttp.go#L214-L238).

I would be fairly straight forward to change that function to return an extended interface, which provides a Content-Length value, when it is easily calculated (i.e. when the input is of type `[]byte`, `string`, or `json.RawMessage`), but these are neither common nor expensive, so probably not worth it, at least at this stage.  All other input types (the `default` case) are serialized by the json stream encoder in real-time.

**Comment by rnewson** [comment]
hmm, fair enough.

I'm obviously tracking the progress on the haproxy mailing list and at some point I'll either have a fix to deploy or will have to temporarily disable http/2 at Cloudant. Almost all the http/2 requests are from browsers, rather than http client libraries like this one. I might see if I can enable it selectively.

**Comment by flimzy** [comment]
@tleyden I just had another thought.  I added the [`couchdb.SetTransport`](https://godoc.org/github.com/go-kivik/couchdb#SetTransport) method in response to #252, which needed to set custom TLS configuration. But a custom transport can also be used to disable HTTP/2 (as #80 demonstrates, in a very crude manner).  So perhaps this would be a reasonable work-around until haproxy/Cloudant are working properly.  Please let me know your thoughts.

Something like this:

    client, err := kivik.New(context.TODO(), "couch", "http://localhost:5984/")
    if err != nil {
        panic(err)
    }

    setXport := couch.SetTransport(&http.Transport{
        	Proxy: http.ProxyFromEnvironment,
        	DialContext: (&net.Dialer{
        		Timeout:   30 * time.Second,
        		KeepAlive: 30 * time.Second,
        		DualStack: true,
        	}).DialContext,
        	MaxIdleConns:          100,
        	IdleConnTimeout:       90 * time.Second,
        	TLSHandshakeTimeout:   10 * time.Second,
        	ExpectContinueTimeout: 1 * time.Second,
        	// a non-empty TLSNextProto map disables HTTP/2 support
        	TLSNextProto: map[string]func(string, *tls.Conn) http.RoundTripper{},
        }
    })

    if err = client.Authenticate(context.TODO(), setXport); err != nil {
    	return nil, err
    }

**Comment by rnewson** [comment]
A fix has appeared in haproxy https://git.haproxy.org/?p=haproxy-1.8.git;a=commit;h=05657bd24ebaf20e5c508a435be9a0830591f033

**Comment by flimzy** [comment]
Thanks for the update @rnewson!  I think that means this issue can now be closed. If any further work is needed, that the work around I proposed above does not address, please feel free to re-open this issue.

**Comment by tleyden** [comment]
Great!  

@flimzy did you still want me to look into that workaround mentioned in https://github.com/go-kivik/couchdb/issues/79#issuecomment-372054715?

**Comment by rnewson** [comment]
I'm waiting for a tagged release (1.8.9, presumably) before beginning the upgrades, but agree that the ticket can close.

**Comment by rnewson** [comment]
1.8.9 is out and includes the fix, so we're deploying that this week.
